services:
  mariadb:
    image: mariadb:10.11
    container_name: cinema-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: luishenrique_tads
      MARIADB_USER: mariadb
      MARIADB_PASSWORD: ${MARIADB_SECRET:-mariadb}
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "mariadb", "-p${MARIADB_SECRET:-mariadb}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: eclipse-temurin:17-jdk-jammy
    container_name: cinema-app
    depends_on:
      mariadb:
       condition: service_started
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: ./mvnw spring-boot:run
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/luishenrique_tads
      SPRING_DATASOURCE_USERNAME: mariadb
      SPRING_DATASOURCE_PASSWORD: ${MARIADB_SECRET:-mariadb}

volumes:
  mariadb_data: