services:
  mariadb:
    image: mariadb:10.11
    container_name: cinema-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: luishenrique_tads
      MARIADB_USER: mariadb
      MARIADB_PASSWORD: mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "mariadb", "-pmariadb"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: eclipse-temurin:17-jdk-jammy
    container_name: cinema-app
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: ./mvnw spring-boot:run -Dspring-boot.run.profiles=docker
    environment:
      SPRING_PROFILES_ACTIVE: docker

volumes:
  mariadb_data: